kind: pipeline
type: docker
name: default

clone:
  depth: 1

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: build
  image: node:alpine
  when:
    event: push
    branch: master
  commands:
    - echo aaa
