kind: pipeline
type: docker
name: default

clone:
  depth: 1

trigger:
  branch:
    - master
  event:
    - push

steps:
- name: build
  image: node:alpine
  when:
    event: push
    branch: master
  environment:
    SECRET_NAME:
      from_secret: name
    SECRET_AGE:
      from_secret: age
  commands:
    - echo $SECRET_NAME $SECRET_AGE $DRONE_COMMIT
