kind: pipeline
type: docker
name: default

clone:
  depth: 1

# trigger:
#   branch:
#     - master
#   event:
#     - push

steps:
- name: test
  image: node:alpine
  when:
    event: push
    branch: test
  environment:
    SECRET_NAME:
      from_secret: name
    SECRET_AGE:
      from_secret: age
  commands:
    - echo $SECRET_NAME $SECRET_AGE $DRONE_BRANCH $DRONE_COMMIT $DRONE_REPO_NAME ${DRONE_BUILD_LINK}
- name: build
  image: node:alpine
  when:
    event: push
    branch: master
  environment:
    SECRET_NAME:
      from_secret: name
    SECRET_AGE:
      from_secret: age
  commands:
    - echo $SECRET_NAME $SECRET_AGE $DRONE_BRANCH $DRONE_COMMIT

# - name: dingtalk
#   image: lddsb/drone-dingtalk-message
#   settings:
#     token:
#       from_secret: token
#     type: markdown
# +   message_color: true

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: ef11bb7c9fd4aa2757625ef083f70ba09f1e23f3385c6188481ce841611dd9b1
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
