language: node_js
node_js:
  - 10
before_install:
  - echo 'before_install'
#install: true # 直接跳过install
# install:
  # - echo 'install'
#script: command1 && command2 # command1成功后才执行command2
script:
  - if [ "$TRAVIS_BRANCH" = "test" ]; then make test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then make release; fi

after_success:
  - echo 'after_success'
# jobs:
#   include:
#     - stage: test
#       script: echo '1'
#     - stage: build
#       script: echo '2'
#       if: (branch = test) AND (NOT(type IN (push, pull_request)))
#     - stage: deploy
#       script: echo '2'
#       if: (branch = test) AND (NOT(type IN (push, pull_request)))

# branches:
#   only:
#     - master
