language: node_js
node_js:
  - 10
env:
  global:
    - CAMPFIRE_TOKEN=abc123
    - TIMEOUT=1000
before_install:
  - echo 'before_install'
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_JOB_ID
  - echo $TRAVIS_JOB_NUMBER
  - echo $token
  - echo $CAMPFIRE_TOKEN

#install: true # 直接跳过install
# install:
  # - echo 'install'
#script: command1 && command2 # command1成功后才执行command2
script:
  - if [ "$TRAVIS_BRANCH" = "test" ]; then make test; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then make release; fi

after_success:
  - echo 'after_success'
# jobs:
#   include:
#     - stage: test
#       script: echo '1'
#     - stage: build
#       script: echo '2'
#       if: (branch = test) AND (NOT(type IN (push, pull_request)))
#     - stage: deploy
#       script: echo '2'
#       if: (branch = test) AND (NOT(type IN (push, pull_request)))

# branches:
#   only:
#     - master
